site_name: Hướng dẫn sử dụng hệ thống vESS

nav:
    - 'Trang chủ': 'saas/saas-introduction.md'
    - 'Đăng ký & cài đặt': 'saas/saas.md'
    - 'Nhân sự': 
        - 'Giới thiệu về phân hệ Quản lý nhân sự': 'hrm/introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'hrm/initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'hrm/abbreviations.md'
        - 'Khai báo danh mục': 'hrm/master-datas.md'
        - 'Tuyển dụng': 'hrm/recruitment.md'
        - 'Hồ sơ nhân viên': 'hrm/employee.md'
        - 'Chấm công': 'hrm/attendance.md'
            # - 'Tiền lương':
        - 'Lịch sử phát triển sản phẩm': 'hrm/log-histories.md'
    - 'Kế toán': 
        - 'Giới thiệu về phân hệ Kế toán': 'finance/fin-introduction.md'
        - 'Thiết lập và khai báo ban đầu': 'finance/fin-initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'finance/fin-abbreviations.md'
        - 'Khai báo danh mục': 'finance/fin-danh-muc-new.md'
        - 'Quản lý tiền': 'finance/fin-tien.md'
        - 'Mua hàng': 'finance/fin-mua-hang.md'
        - 'Bán hàng': 'finance/fin-ban-hang.md'
        - 'Kế toán tổng hợp': 'finance/fin-ke-toan-tong-hop.md'
        - 'Kho vận': 'finance/fin-kho.md'
        - 'Sản xuất': 'finance/fin-san-xuat.md'
        - 'Tài sản cố định': 'finance/fin-tscd.md'
        - 'Công cụ dụng cụ': 'finance/fin-ccdc.md'
        - 'Lịch sử phát triển sản phẩm': 'finance/fin-log-histories.md'
    - 'Digital workplace': 
        - 'Giới thiệu về phân hệ Digital workplace': 'digitalworkplace/Gioi-thieu-digital-workplace.md'
        - 'Thiết lập và khai báo ban đầu': 'digitalworkplace/dw-initialization.md'
        - 'Các thuật ngữ và từ viết tắt': 'digitalworkplace/Thuat-ngu-viet-tat.md'
        - 'Đăng nhập, đăng xuất': 'digitalworkplace/Addon-login.md'
        - 'Trang web': 'digitalworkplace/Addon-Website.md'
        - 'Khảo sát': 'digitalworkplace/Addon-khao-sat.md'
        - 'Ghi chú': 'digitalworkplace/Addon-ghi-chu.md'
        - 'Timesheet': 'digitalworkplace/Addon-timesheet.md'
        - 'Sự kiện': 'digitalworkplace/Addon-su-kien.md'
        - 'Lịch sử phát triển sản phẩm': 'digitalworkplace/Lich-su-phat-trien.md'
    - 'Release Notes': 'release-notes.md'
theme:
    name: readthedocs
    navigation_depth: 100
    highlightjs: true
extra_css:
    - css/extra.css